## Import Library

In [1]:
import tensorflow as tf
import numpy as np

### Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor
### membuat tensor menggunakan tf.random.normal

In [21]:
random_tensor = tf.random.normal([5,5], mean=0., stddev=1., seed=1)
random_tensor.numpy()

array([[-0.32386488,  0.99133694,  0.14024267,  1.2573972 ,  0.09992335],
       [ 0.18983224, -0.28711194, -1.7413595 ,  1.8718754 , -2.0104504 ],
       [-1.4673029 , -1.2721989 , -0.7803738 ,  0.94073033, -0.06164822],
       [-2.0842526 ,  0.61423135, -1.451092  , -0.88693523, -0.96740866],
       [ 0.94831836, -0.6974499 ,  0.5391437 , -0.52970064, -2.0105364 ]],
      dtype=float32)

### Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prima_tensor
### menggunakan tf.constant

In [22]:
list_bill_prima = [[2, 3, 5, 7, 11],[13, 17, 19, 23, 29],[31, 37, 41, 43, 47],[53, 59, 61, 71, 73],[79, 83, 89, 97, 1]]

bill_prima_tensor = tf.constant(list_bilprim, dtype=tf.float32) 
bill_prima_tensor.numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 71., 73.],
       [79., 83., 89., 97.,  1.]], dtype=float32)

### Tampilkan dimensi dari kedua variable tersebut
### dimensi dari variabel random_tensor menggunakan perintah shape

In [23]:
random_tensor.shape 

TensorShape([5, 5])

### dimensi dari variabel bill_prima_tensor menggunakan perintah shape

In [25]:
bill_prima_tensor.shape

TensorShape([5, 5])

### Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

In [31]:
print("Pengurangan :",tf.subtract(bill_prima_tensor,random_tensor))

Pengurangan : tf.Tensor(
[[ 2.323865   2.0086632  4.8597574  5.742603  10.900077 ]
 [12.810167  17.287111  20.74136   21.128124  31.01045  ]
 [32.467304  38.272198  41.780373  42.05927   47.06165  ]
 [55.08425   58.38577   62.45109   71.88693   73.96741  ]
 [78.05168   83.69745   88.46085   97.5297     3.0105364]], shape=(5, 5), dtype=float32)


In [32]:
print("Pembagian :",tf.divide(bill_prima_tensor,random_tensor))

Pembagian : tf.Tensor(
[[-6.17541504e+00  3.02621627e+00  3.56524887e+01  5.56705570e+00
   1.10084381e+02]
 [ 6.84815216e+01 -5.92103577e+01 -1.09110155e+01  1.22871428e+01
  -1.44246283e+01]
 [-2.11271992e+01 -2.90835018e+01 -5.25389252e+01  4.57091675e+01
  -7.62390198e+02]
 [-2.54287796e+01  9.60550156e+01 -4.20373077e+01 -8.00509415e+01
  -7.54593201e+01]
 [ 8.33053589e+01 -1.19004959e+02  1.65076584e+02 -1.83122299e+02
  -4.97379690e-01]], shape=(5, 5), dtype=float32)


In [33]:
print("Penjumlahan :",tf.add(bill_prima_tensor,random_tensor))

Penjumlahan : tf.Tensor(
[[ 1.6761351  3.9913368  5.1402426  8.257397  11.099923 ]
 [13.189833  16.712889  17.25864   24.871876  26.98955  ]
 [29.532698  35.727802  40.219627  43.94073   46.93835  ]
 [50.91575   59.61423   59.54891   70.11307   72.03259  ]
 [79.94832   82.30255   89.53915   96.4703    -1.0105364]], shape=(5, 5), dtype=float32)


In [34]:
print("Perkalian :",tf.multiply(bill_prima_tensor,random_tensor))

Perkalian : tf.Tensor(
[[  -0.64772975    2.974011      0.70121336    8.801781      1.0991569 ]
 [   2.4678192    -4.880903    -33.08583      43.053135    -58.303062  ]
 [ -45.48639     -47.07136     -31.995327     40.451405     -2.8974664 ]
 [-110.465385     36.23965     -88.51661     -62.9724      -70.620834  ]
 [  74.91715     -57.888344     47.983788    -51.380962     -2.0105364 ]], shape=(5, 5), dtype=float32)


In [36]:
print("Logaritma :",tf.math.log(bill_prima_tensor,random_tensor))

Logaritma : tf.Tensor(
[[0.6931472 1.0986123 1.609438  1.9459102 2.3978953]
 [2.5649493 2.8332133 2.944439  3.1354942 3.3672957]
 [3.4339871 3.610918  3.713572  3.7612002 3.8501477]
 [3.9702919 4.0775375 4.1108737 4.26268   4.2904596]
 [4.3694477 4.4188404 4.4886365 4.574711  0.       ]], shape=(5, 5), dtype=float32)


### Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [37]:
tf.argmax(random_tensor, axis=1). numpy()

array([3, 3, 3, 1, 0], dtype=int64)

In [38]:
tf.argmin(random_tensor, axis=1). numpy()

array([0, 4, 0, 0, 4], dtype=int64)

In [39]:
tf.argmax(random_tensor, axis=0). numpy()

array([4, 0, 4, 1, 0], dtype=int64)

In [40]:
tf.argmin(random_tensor, axis=0). numpy()

array([3, 2, 1, 3, 4], dtype=int64)

### Tampilkan hasil dari penggabungan variable random_tensor dengan prima_tensor (concatenation)

In [41]:
tf.concat([random_tensor, bill_prima_tensor], axis=1)

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[-3.2386488e-01,  9.9133694e-01,  1.4024267e-01,  1.2573972e+00,
         9.9923350e-02,  2.0000000e+00,  3.0000000e+00,  5.0000000e+00,
         7.0000000e+00,  1.1000000e+01],
       [ 1.8983224e-01, -2.8711194e-01, -1.7413595e+00,  1.8718754e+00,
        -2.0104504e+00,  1.3000000e+01,  1.7000000e+01,  1.9000000e+01,
         2.3000000e+01,  2.9000000e+01],
       [-1.4673029e+00, -1.2721989e+00, -7.8037381e-01,  9.4073033e-01,
        -6.1648224e-02,  3.1000000e+01,  3.7000000e+01,  4.1000000e+01,
         4.3000000e+01,  4.7000000e+01],
       [-2.0842526e+00,  6.1423135e-01, -1.4510920e+00, -8.8693523e-01,
        -9.6740866e-01,  5.3000000e+01,  5.9000000e+01,  6.1000000e+01,
         7.1000000e+01,  7.3000000e+01],
       [ 9.4831836e-01, -6.9744992e-01,  5.3914368e-01, -5.2970064e-01,
        -2.0105364e+00,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
         9.7000000e+01,  1.0000000e+00]], dtype=float32)>

In [42]:
tf.concat([random_tensor, bill_prima_tensor], axis=0)

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[-3.2386488e-01,  9.9133694e-01,  1.4024267e-01,  1.2573972e+00,
         9.9923350e-02],
       [ 1.8983224e-01, -2.8711194e-01, -1.7413595e+00,  1.8718754e+00,
        -2.0104504e+00],
       [-1.4673029e+00, -1.2721989e+00, -7.8037381e-01,  9.4073033e-01,
        -6.1648224e-02],
       [-2.0842526e+00,  6.1423135e-01, -1.4510920e+00, -8.8693523e-01,
        -9.6740866e-01],
       [ 9.4831836e-01, -6.9744992e-01,  5.3914368e-01, -5.2970064e-01,
        -2.0105364e+00],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  7.1000000e+01,
         7.3000000e+01],
       [ 7.9000000e+01,  8.3000000e+01,  8.9000000e+01,  9.7000000e+01,
      

### Tampilkan hasil sorting dari kedua variable di atas. (descending)

In [43]:
sort_random_tensor0 = tf.sort(random_tensor, direction="DESCENDING") 
sort_random_tensor0.numpy()

array([[ 1.2573972 ,  0.99133694,  0.14024267,  0.09992335, -0.32386488],
       [ 1.8718754 ,  0.18983224, -0.28711194, -1.7413595 , -2.0104504 ],
       [ 0.94073033, -0.06164822, -0.7803738 , -1.2721989 , -1.4673029 ],
       [ 0.61423135, -0.88693523, -0.96740866, -1.451092  , -2.0842526 ],
       [ 0.94831836,  0.5391437 , -0.52970064, -0.6974499 , -2.0105364 ]],
      dtype=float32)

In [44]:
sort_bill_prima_tensor0 = tf.sort(bill_prima_tensor, direction="DESCENDING")
sort_bill_prima_tensor0.numpy()

array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [73., 71., 61., 59., 53.],
       [97., 89., 83., 79.,  1.]], dtype=float32)

In [45]:
sort_random_tensor1 = tf.argsort(random_tensor, direction="DESCENDING") 
sort_random_tensor1.numpy()

array([[3, 1, 2, 4, 0],
       [3, 0, 1, 2, 4],
       [3, 4, 2, 1, 0],
       [1, 3, 4, 2, 0],
       [0, 2, 3, 1, 4]])

In [47]:
sort_bill_prima_tensor1 = tf.argsort(bill_prima_tensor, direction="DESCENDING")
sort_bill_prima_tensor1.numpy()

array([[4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [3, 2, 1, 0, 4]])